import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#dfe2ee",
        "tertiary-fixed-dim": "#2fd9f4",
        "primary-container": "#06b6d4",
        "inverse-on-surface": "#2c3039",
        "secondary-container": "#571bc1",
        "surface-dim": "#0f131c",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#00363e",
        "surface-container-high": "#262a33",
        "on-error": "#690005",
        "on-primary-fixed": "#001f26",
        "surface-container-highest": "#31353e",
        primary: "#4cd7f6",
        "on-primary-container": "#00424f",
        "on-secondary": "#3c0091",
        "surface-tint": "#4cd7f6",
        "on-background": "#dfe2ee",
        "on-secondary-fixed": "#23005c",
        "surface-container": "#1c2028",
        secondary: "#d0bcff",
        "secondary-fixed": "#e9ddff",
        "on-secondary-fixed-variant": "#5516be",
        "primary-fixed-dim": "#4cd7f6",
        "surface-variant": "#31353e",
        background: "#0f131c",
        "error-container": "#93000a",
        "surface-container-low": "#181c24",
        "on-tertiary-container": "#00434d",
        "on-tertiary-fixed": "#001f25",
        "on-secondary-container": "#c4abff",
        error: "#ffb4ab",
        "outline-variant": "#3d494c",
        "on-surface-variant": "#bcc9cd",
        "on-primary-fixed-variant": "#004e5c",
        surface: "#0f131c",
        "inverse-surface": "#dfe2ee",
        "surface-container-lowest": "#0a0e16",
        "inverse-primary": "#00687a",
        outline: "#869397",
        "primary-fixed": "#acedff",
        "on-primary": "#003640",
        tertiary: "#2fd9f4",
        "secondary-fixed-dim": "#d0bcff",
        "surface-bright": "#353942",
        "tertiary-fixed": "#a2eeff",
        "tertiary-container": "#00b7cf",
        "on-tertiary-fixed-variant": "#004e5a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "margin-mobile": "0.75rem",
        "gutter-mobile": "0.5rem",
        gutter: "1rem",
        "gutter-tablet": "0.75rem",
        "space-sm": "0.5rem",
        margin: "1.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        "margin-tablet": "1rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "code-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "title-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        geist: ["Geist", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "label-xs": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "title-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "500" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        dash: "dash 20s linear infinite",
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "glow-pulse": "glowPulse 2s ease-in-out infinite",
      },
      keyframes: {
        dash: {
          to: { strokeDashoffset: "-100" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 16px rgba(6,182,212,0.35)" },
          "50%": { boxShadow: "0 0 32px rgba(6,182,212,0.65)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
